UBICACIONES_GUADALAJARA_DE_BUGA = {
    'Chambimbal': 'Guadalajara de Buga',
    'San Antonio': 'Guadalajara de Buga',
    'La Campiña': 'Guadalajara de Buga',
    'Cerrorico': 'Guadalajara de Buga',
    'Quebradaseca': 'Guadalajara de Buga',
    'El Manantial': 'Guadalajara de Buga',
    'Zanjón Hondo': 'Guadalajara de Buga',
    'Sonsito': 'Guadalajara de Buga',
    'Urbanización La Unidad': 'Guadalajara de Buga',
    'Pueblo Nuevo': 'Guadalajara de Buga',
    'El Porvenir': 'Guadalajara de Buga',
    'Pueblo Bertín': 'Guadalajara de Buga',
    'La Palomera': 'Guadalajara de Buga',
    'El Vínculo': 'Guadalajara de Buga',
    'urbanización El Bosque': 'Guadalajara de Buga',
    'La Habana': 'Guadalajara de Buga',
    'La Magdalena': 'Guadalajara de Buga',
    'Las Frías': 'Guadalajara de Buga',
    'Alaska': 'Guadalajara de Buga',
    'El Diamante': 'Guadalajara de Buga',
    'Guadualejo': 'Guadalajara de Buga',
    'La Planta': 'Guadalajara de Buga',
    'Alto Cielo': 'Guadalajara de Buga',
    'La Piscina': 'Guadalajara de Buga',
    'El Janeiro': 'Guadalajara de Buga',
    'La Cabaña': 'Guadalajara de Buga',
    'La María': 'Guadalajara de Buga',
    'La Primavera': 'Guadalajara de Buga',
    'Los Medios': 'Guadalajara de Buga',
    'Urbanización Los Totumos': 'Guadalajara de Buga',
    'Monterrey': 'Guadalajara de Buga',
    'La Unión': 'Guadalajara de Buga',
    'Miravalle': 'Guadalajara de Buga',
    'Rosario de Fátima': 'Guadalajara de Buga',
    'San José': 'Guadalajara de Buga',
    'Miraflores': 'Guadalajara de Buga',
    'Frisoles': 'Guadalajara de Buga',
    'La Florida': 'Guadalajara de Buga',
    'El Placer': 'Guadalajara de Buga',
    'El Rosario': 'Guadalajara de Buga',
    'Santa Rita': 'Guadalajara de Buga',
    'Santa Rosa': 'Guadalajara de Buga',
    'El Salado': 'Guadalajara de Buga',
    'San Agustín': 'Guadalajara de Buga',
    'Crucero Nogales': 'Guadalajara de Buga',
    'La Playa del Buey': 'Guadalajara de Buga',
    'El Topacio': 'Guadalajara de Buga',
    'La Mesa - Rioloro': 'Guadalajara de Buga',
    'Los Bancos': 'Guadalajara de Buga',
    'El Jardín': 'Guadalajara de Buga',
    'Las Ventas': 'Guadalajara de Buga',
    'El Arbolito': 'Guadalajara de Buga',
    'Refugio Campestre (Zanjón Hondo)': 'Guadalajara de Buga',
    'Mira Lindo': 'Guadalajara de Buga',
    'Lomas del Albergue': 'Guadalajara de Buga',
    'Parcelación campestre Miravalle': 'Guadalajara de Buga',
    'Albores Lomas del Albergue': 'Guadalajara de Buga',
    'Parcelación campestre Mirador Altamira': 'Guadalajara de Buga',
    'Parcelación Campestre La Diana (La Primavera)': 'Guadalajara de Buga',
    'Parcelación campestre Montearroyo': 'Guadalajara de Buga',
    'Parcelación campestre Altos de Montearroyo': 'Guadalajara de Buga',
    'Parcelación El Retoño': 'Guadalajara de Buga',
    'Parcelación campestre Kiku': 'Guadalajara de Buga',
    'Parcelación campestre Zión Riveras de Guadalajara': 'Guadalajara de Buga',
    'Parcelación campestre El Edén': 'Guadalajara de Buga',
    'Parcelación campestre Río Milagroso': 'Guadalajara de Buga',
    'El Descanso del Rey (La Magdalena)': 'Guadalajara de Buga',
    'Santiago Vergara Crespo': 'Guadalajara de Buga',
    'El Molino': 'Guadalajara de Buga',
    'Alto Bonito': 'Guadalajara de Buga',
    'La Revolución': 'Guadalajara de Buga',
    'La Esperanza': 'Guadalajara de Buga',
    'Santa Bárbara': 'Guadalajara de Buga',
    'Fuenmayor': 'Guadalajara de Buga',
    'Divino Niño': 'Guadalajara de Buga',
    'Sucre': 'Guadalajara de Buga',
    'Palo Blanco': 'Guadalajara de Buga',
    'La Concordia': 'Guadalajara de Buga',
    'José María Cabal': 'Guadalajara de Buga',
    'Ricaurte': 'Guadalajara de Buga',
    'La Merced': 'Guadalajara de Buga',
    'Alejandro Cabal Pombo': 'Guadalajara de Buga',
    'María Luisa de la Espada': 'Guadalajara de Buga',
    'Popular': 'Guadalajara de Buga',
    'La Ventura': 'Guadalajara de Buga',
    'La Honda': 'Guadalajara de Buga',
    'El Albergue': 'Guadalajara de Buga',
    'El Carmelo': 'Guadalajara de Buga',
    'Estambul': 'Guadalajara de Buga',
    'Altamira': 'Guadalajara de Buga',
    'Prados de Oriente': 'Guadalajara de Buga',
    'San Vicente': 'Guadalajara de Buga',
    'Condominio San Andrés': 'Guadalajara de Buga',
    'Altos de Guadalajara': 'Guadalajara de Buga',
    'Los Almendros': 'Guadalajara de Buga',
    'Bello Horizonte': 'Guadalajara de Buga',
    'Las Palmitas': 'Guadalajara de Buga',
    'Las Palmas': 'Guadalajara de Buga',
    'Coviprob': 'Guadalajara de Buga',
    'Valle Real': 'Guadalajara de Buga',
    'San José de las Palmas': 'Guadalajara de Buga', 
    'Albores de San Juanito': 'Guadalajara de Buga', 
    'Condominio San José del Parque': 'Guadalajara de Buga', 
    'Acuarelas del Valle': 'Guadalajara de Buga', 
    'Aures': 'Guadalajara de Buga', 
    'Remanso de Aures': 'Guadalajara de Buga', 
    'Condominio Portales del Río': 'Guadalajara de Buga', 
    'Condominio Lourdes': 'Guadalajara de Buga', 
    'Los Ángeles': 'Guadalajara de Buga', 
    'Condominio la Alameda': 'Guadalajara de Buga', 
    'La Catalina': 'Guadalajara de Buga', 
    'Prados de la Julia': 'Guadalajara de Buga', 
    'Prados del Sur': 'Guadalajara de Buga', 
    'Capri': 'Guadalajara de Buga', 
    'Condominio Aures': 'Guadalajara de Buga', 
    'La Julia': 'Guadalajara de Buga', 
    'Condominio Rincón del Guadalajara': 'Guadalajara de Buga', 
    'Compostela': 'Guadalajara de Buga', 
    'Torres de Alicante': 'Guadalajara de Buga', 
    'Jorge Eliecer Gaitán': 'Guadalajara de Buga', 
    'San Marino': 'Guadalajara de Buga', 
    'El Edén': 'Guadalajara de Buga', 
    'El Milagro': 'Guadalajara de Buga', 
    'Los Rosales': 'Guadalajara de Buga', 
    'El Samán': 'Guadalajara de Buga', 
    'Caracolí': 'Guadalajara de Buga', 
    'Balboa': 'Guadalajara de Buga', 
    'Villa Pachita': 'Guadalajara de Buga', 
    'Prados del Norte': 'Guadalajara de Buga', 
    'Ciudadela Comfenalco': 'Guadalajara de Buga', 
    'Montellano': 'Guadalajara de Buga', 
    'Brisas del Norte': 'Guadalajara de Buga', 
    'Los Samanes': 'Guadalajara de Buga', 
    'Balcones del Norte': 'Guadalajara de Buga', 
    'UniNorte': 'Guadalajara de Buga', 
    'Entre Valles': 'Guadalajara de Buga', 
    'Ana María': 'Guadalajara de Buga', 
    'Lombardía': 'Guadalajara de Buga', 
    'San José Obrero': 'Guadalajara de Buga', 
    'Buganvilla': 'Guadalajara de Buga', 
    'San Gerónimo': 'Guadalajara de Buga', 
    'San Miguel': 'Guadalajara de Buga', 
    'Condominio el Portal': 'Guadalajara de Buga', 
    'Condominio del Albergue': 'Guadalajara de Buga'
}